scmAppsetRequeueAfterSeconds: 30

destinationClusters:
  - name: in-cluster
    allowedTeams: [".*"]

multiStageKargoAppSetHelmRepo: "https://github.com/suxess-it/kubriX"

teams:
  - name: team1
    sourceRepos:
      - '*'
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
      - group: kargo.akuity.io
        kind: Project
    appOfAppsRepo:
      repoURL: https://github.com/lorenzofini01/team1-apps
      path: codespaces-apps
      revision: main
    multiStageKargoAppSet:
      organization: lorenzofini01